"""add failed_files table

Revision ID: 174e3d785bd0
Revises: 8efddff21ca9
Create Date: 2026-04-08 14:22:32.282748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174e3d785bd0'
down_revision: Union[str, Sequence[str], None] = '8efddff21ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_run_id', sa.Integer(), nullable=False),
    sa.Column('file_meta', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('crawl_jobs', 'failure_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crawl_jobs', 'failure_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('failed_files')
    # ### end Alembic commands ###
