"""Add is_active, is_deleted, user_email, user_id to credentials

Revision ID: 3fe8aca16a1a
Revises: f73d2e56878d
Create Date: 2026-04-06 16:12:38.098269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe8aca16a1a'
down_revision: Union[str, Sequence[str], None] = 'f73d2e56878d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('credentials', sa.Column('user_email', sa.String(), nullable=False))
    op.add_column('credentials', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('credentials', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'is_deleted')
    op.drop_column('credentials', 'is_active')
    op.drop_column('credentials', 'user_email')
    op.drop_column('credentials', 'user_id')
    # ### end Alembic commands ###
