"""add run_type to crawl_runs

Revision ID: 4deb0131c52f
Revises: ebeb01594696
Create Date: 2026-03-24 15:21:58.586028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4deb0131c52f'
down_revision: Union[str, Sequence[str], None] = 'ebeb01594696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_runs', sa.Column('run_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_runs', 'run_type')
    # ### end Alembic commands ###
