"""add connector_types and connector_field_schemas tables

Revision ID: 66a3436cf06e
Revises: 4deb0131c52f
Create Date: 2026-03-26 18:31:02.617052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a3436cf06e'
down_revision: Union[str, Sequence[str], None] = '4deb0131c52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
