"""add connector_types and connector_field_schemas tables

Revision ID: f73d2e56878d
Revises: 66a3436cf06e
Create Date: 2026-03-26 18:39:28.335237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73d2e56878d'
down_revision: Union[str, Sequence[str], None] = '66a3436cf06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('auth_type', sa.String(), nullable=False),
    sa.Column('oauth_url', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type')
    )
    op.create_table('connector_field_schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_type_id', sa.Integer(), nullable=False),
    sa.Column('field_category', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_type_id'], ['connector_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connector_field_schemas')
    op.drop_table('connector_types')
    # ### end Alembic commands ###
